// Generated by WebFx

module webfx.demo.colorfulcircles.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;

    // Exported packages
    exports dev.webfx.demo.colorfulcircles;

    // Provided services
    provides javafx.application.Application with dev.webfx.demo.colorfulcircles.ColorfulCircles;

}